### ISSUE TITLE
게시판 만들기

### ISSUE THREAD

**Issue by AnemoneCoronaria** [PTU-Java-team/PTUproject#2]
게시판 만들어야함

메인 웹 페이지에 고객 센터에 게시판 기능 사용해야함

**Comment by 99ibin** [comment]
구현은 정상화
디자인과 UI 구상 필요 ( 사이드 바로 넘기는 작업

**Comment by 99ibin** [comment]
게시판 ID랑 if문 사용해서 안맞으면 작성 안되게 할것
