### ISSUE TITLE
상품 데이터베이스

### ISSUE THREAD

**Issue by AnemoneCoronaria** [PTU-Java-team/PTUproject#5]

**Comment by AnemoneCoronaria** [comment]
CREATE SEQUENCE moll_seq
    START WITH 1
    INCREMENT BY 1
    nocache;
-- 시퀀스 생성 왼료

create table catagory_table (
    category_id int primary key,
    category_id2 int,
    category_name varchar(20)
);
--트리거
create or replace trigger trg_auto_increment_category
    before insert on catagory_table
    for each row
    begin
        :new.catagory_id := moll_seq.nextval;
    end;


create table product_table (
    product_id int primary key,
    product_name varchar(150),
    product_img1 varchar(600),
    product_img2 varchar(600),
    product_img3 Blob,      -- 이건 그냥 작성해본것
    product_description varchar(1200),
    product_price int,
    product_date DATE,
    category_id2 int,  -- 외래 키로 사용할 컬럼 추가
    FOREIGN KEY (category_id2) REFERENCES category_table(category_id)  -- 외래 키 제약 조건 추가
);
--트리거
create or replace trigger trg_auto_increment_product
    before insert on product_table
    for each row
    begin
        :new.produnt_id := moll_seq.nextval;
    end;

create table comment_table (
    comment_id int primary key ,
    comment_content varchar(300),
    comment_rate date   --이거 datetime 이 오라클에는 없음
    admin_num int,
    FOREIGN KEY (admin_num) REFERENCES admin_table(admin_num)
                           --게시글 번호 아직 반영 안함
);
--트리거
create or replace trigger trg_auto_increment_comment
    before insert on comment_table
    for each row
    begin
        :new.comment_id := moll_seq.nextval;
    end;

create table admin_table (
    admin_num int primary key ,
    admin_id varchar(20),
    admin_password varchar(50)
);
--트리거
create or replace trigger trg_auto_increment_admin
    before insert on admin_table
    for each row
    begin
        :new.admin_num := moll_seq.nextval;
    end;

create table board_table (
    board_id int primary key ,
    board_title varchar(100),
    board_redate date,      --datetime 없어서 date로 일단 작성
    board_content varchar(300),
    board_img varchar(600),
    product_id int,
    foreign key (product_id) references product_table(product_id),
    category_name varchar(30),
    --foreign key (category_name) references catagory_table(category_id)
);
-- 게시판 카테고리 외래 키는 category_id로 변경해야 함
ALTER TABLE board_table
    ADD FOREIGN KEY (category_name) REFERENCES category_table(category_name);

--트리거
create or replace trigger trg_auto_increment_board
    before insert on board_table
    for each row
    begin
        :new.board_id := moll_seq.nextval;
    end;


create table members_table (
    members_id int primary key ,
    members_email varchar(50),
    members_name varchar(150),
    members_age int,
    members_mobile varchar(15),
    members_signout varchar(1)
);
--트리거
create or replace trigger trg_auto_increment_members
    before insert on members_table
    for each row
    begin
        :new.members_id := moll_seq.nextval;
    end;

create table adminboard_table (
    notice_id int primary key ,
    admin_id int,
    board_type varchar(5),
    board_title varchar(15),
    board_view int,
    board_date date
);
--트리거
create or replace trigger trg_auto_increment_adminboard
    before insert on admin_table
    for each row
    begin
        :new.notice_id := moll_seq.nextval;
    end;

create table orderlist_table (
    order_id int primary key ,
    order_price int,
    order_img varchar(600),
    members_id int,
    foreign key (members_id) references members_table(members_id),
    produnt_id int,
    foreign key (product_id) references product_table(product_id),
)

**Comment by AnemoneCoronaria** [comment]
잘못된 오류가 속출할 수 있음... 
유의바람😊

**Comment by AnemoneCoronaria** [comment]
상단은 오류 속출
오류 수정본은 하단

**Comment by AnemoneCoronaria** [comment]
CREATE SEQUENCE moll_seq
    START WITH 1
    INCREMENT BY 1
    nocache;
-- 시퀀스 생성 왼료

create table category_table (
    category_id int primary key,
    category_id2 int,
    category_name varchar(20)
);
--트리거
create or replace trigger trg_auto_increment_category
    before insert on category_table
    for each row
    begin
        :new.category_id := moll_seq.nextval;
    end;


create table product_table (
    product_id int primary key,
    product_name varchar(150),
    product_img1 varchar(600),
    product_img2 varchar(600),
    product_img3 Blob,      -- 이건 그냥 작성해본것
    product_description varchar(1200),
    product_price int,
    product_date DATE default SYSDATE,
    category_id2 int,  -- 외래 키로 사용할 컬럼 추가
    FOREIGN KEY (category_id2) REFERENCES category_table(category_id)  -- 외래 키 제약 조건 추가
);
-- 트리거
CREATE OR REPLACE TRIGGER trg_auto_increment_product
    BEFORE INSERT ON product_table
    FOR EACH ROW
BEGIN
    IF :new.product_id IS NULL THEN  -- product_id가 NULL일 때만 시퀀스를 사용
        :new.product_id := moll_seq.NEXTVAL;
    END IF;
END;

create table comment_table (
    comment_id int primary key ,
    comment_content varchar(300),
    comment_rate date,   --이거 datetime 이 오라클에는 없음
    admin_num int,
    FOREIGN KEY (admin_num) REFERENCES admin_table(admin_num)
                           --게시글 번호 아직 반영 안함
);
--트리거
create or replace trigger trg_auto_increment_comment
    before insert on comment_table
    for each row
    begin
        :new.comment_id := moll_seq.nextval;
    end;

create table admin_table (
    admin_num int primary key ,
    admin_id varchar(20),
    admin_password varchar(50)
);
--트리거
create or replace trigger trg_auto_increment_admin
    before insert on admin_table
    for each row
    begin
        :new.admin_num := moll_seq.nextval;
    end;

create table board_table (
    board_id int primary key ,
    board_title varchar(100),
    board_redate date,      --datetime 없어서 date로 일단 작성
    board_content varchar(300),
    board_img varchar(600),
    product_id int,
    foreign key (product_id) references product_table(product_id),
    category_name varchar(30)
    --foreign key (category_name) references catagory_table(category_id)
);
-- 게시판 카테고리 외래 키는 category_id로 변경해야 함
ALTER TABLE board_table
    ADD FOREIGN KEY (category_name) REFERENCES category_table(category_name);

--트리거
create or replace trigger trg_auto_increment_board
    before insert on board_table
    for each row
    begin
        :new.board_id := moll_seq.nextval;
    end;


create table members_table (
    members_id int primary key ,
    members_email varchar(50),
    members_name varchar(150),
    members_age int,
    members_mobile varchar(15),
    members_signout varchar(1)
);
--트리거
create or replace trigger trg_auto_increment_members
    before insert on members_table
    for each row
    begin
        :new.members_id := moll_seq.nextval;
    end;

create table adminboard_table (
    notice_id int primary key ,
    admin_id int,
    board_type varchar(5),
    board_title varchar(15),
    board_view int,
    board_date date
);
-- 트리거
CREATE OR REPLACE TRIGGER trg_auto_increment_adminboard
    BEFORE INSERT ON adminboard_table  -- 수정: admin_table -> adminboard_table
    FOR EACH ROW
BEGIN
    :new.notice_id := moll_seq.NEXTVAL;  -- 이제 notice_id가 올바른 테이블에 대해 설정됨
END;


create table orderliness_table (
    order_id int primary key ,
    order_price int,
    order_img varchar(600),
    members_id int,
    foreign key (members_id) references members_table(members_id),
    product_id int,
    foreign key (product_id) references product_table(product_id)
);
--트리거
create or replace trigger trg_auto_increment_orderlist
    before insert on orderliness_table
    for each row
    begin
        :new.order_id := moll_seq.nextval;
    end;

**Comment by AnemoneCoronaria** [comment]
이전 내용은 삭제하고 수정본 올렸습니다.
가장 위에 있는 시퀀스는 한번만 하시면 됩니다.
그 이외는 테이블과 트리거를 한 쌍으로 드래그해서 실행하시면 됩니다.

추가로 오류 발생하거나 안되면 
      오류 메시지와 오류 발생 코드 묶음으로 올려주시길 바랍니다.

**Comment by AnemoneCoronaria** [comment]
[Wallet_team.zip](https://github.com/user-attachments/files/17437756/Wallet_team.zip)


위에 파일은 클라우드 전자 지갑 입니다. 다운로드 받고 zip 파일 그대로 놔둡니다.

이제 sql 디벨로퍼에 들어가서 접속에서 추가(초록생 십자) 버튼을 누릅니다.

상단에 name은 대충 기억에 남는 적절한 원하는 이름 넣으시면 됩니다.

그 이후 아래에
사용자 이름이나 비밀번호는 제가 만들어 놓은 딱 2가지가 있습니다.

이름 : MEMBER1
비번 : Anemone12345

이름 : MEMBER2
비번 : Anemone12345

관리자 계정
이름 : admin
비번 : Anemone12345

두 가지를 만들었습니다.

그 밑에 접속 유형은 클라우드 전자지갑 선택 후 처음에 받은 zip 파일로 설정합니다.

그 후 테스트한 다음 연결되면 저장 후 접속하기

추가로
다 된 다음에 sql 코드 입력할 수 있는 워크시트가 생기면

show user;

를 해보면 유저가 누가 있는지 볼 수 있습니다.

해봤는데 안될 수도 있습니다......
저도 제것만 연결해봐서 ;;;;

제 클라우드에 사용자는 위에 멤버1, 2와 같이 추가하긴 했습니다.

안되면 알려주시면 다른 방법 찾아보겠습니다.

**Comment by 99ibin** [comment]
@뒤에 입력하면 연결됩니다(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-chuncheon-1.oraclecloud.com))(connect_data=(service_name=gbdc3dba096d125_team_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))

**Comment by ggggene** [comment]
[IntelliJ, DataGrip에서 Oracle cloud 접속하기](https://monique.tistory.com/24)

**Comment by 99ibin** [comment]
1. 메인 페이지에서 website와 smallgroup으로 연결되었을때 카테고리를 통한 listup을 해야한다
2. 카테고리를 통한 삭제와 저장은 필요한가?
/ 카테고리
    private final category_Service categoryService;

    
    // 모든 카테고리 조회
    @GetMapping("/")
    public String findAllCategories(Model model) {
        List<category_tableDTO> categoryList = categoryService.findAllCategories();
        model.addAttribute("categories", categoryList);
        return "/";  // category 목록 페이지로 이동
    }

    // 특정 카테고리 조회
    @GetMapping("/")
    public String findCategoryById(@RequestParam("id") int categoryId, Model model) {
        category_tableDTO category = categoryService.findCategoryById(categoryId);
        model.addAttribute("category", category);
        return "/"; // 카테고리 상세 페이지로 이동
    }
    카테고리를 통한 webpage와 smallgroup이 어떻게 나눌건지

**Comment by AnemoneCoronaria** [comment]
member 테이블에 관리자 유무 파악 isAdmin 추가하는 방법
INSERT INTO member_table (MEMBEREMAIL, MEMBERPASSWORD, MEMBERNAME, MEMBERAGE, MEMBERMOBILE, isAdmin)
VALUES ('admin@ptu.com', '1234', 'Admin', '100', '010-1234-5678', 1);

커밋 작성해야 값이 실제로 테이블에 반영이 될 수 있음
commit ;

만약 테이블 안에서 데이터를 이메일 기준으로 지정해서 삭제하고 싶을 때
DELETE FROM member_table WHERE memberemail = 'admin@example.com';

**Comment by ggggene** [comment]
저희 기존 DB 안에 product_table의 컬럼 중에서 category_id2 -> category_id로 변경 했습니다.

-- product_table의 category_id 컬럼 생성
alter table PRODUCT_TABLE add category_id int;  

-- product_table의 category_id2 컬럼 삭제
alter table PRODUCT_TABLE DROP COLUMN category_id2; 

-- product_table의 category_id에 fk 키 제약조건 부여
alter table PRODUCT_TABLE add constraint category_fk foreign key (CATEGORY_ID) references CATEGORY_TABLE (CATEGORY_ID);
select * from PRODUCT_TABLE;

**Comment by ggggene** [comment]
# mysql 코드


-- 테이블 생성 SQL - category_table
CREATE TABLE category_table
(
    category_id      INT            NOT NULL, 
    category_name    VARCHAR(30)    NOT NULL, 
     PRIMARY KEY (category_id)
);

-- Auto Increment를 위한 Sequence 추가 SQL - category_table.category_id
CREATE SEQUENCE category_table_SEQ
START WITH 1
INCREMENT BY 1;

-- Auto Increment를 위한 Trigger 추가 SQL - category_table.category_id
CREATE OR REPLACE TRIGGER category_table_AI_TRG
BEFORE INSERT ON category_table 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT category_table_SEQ.NEXTVAL
    INTO :NEW.category_id
    FROM DUAL;
END;

-- DROP TRIGGER category_table_AI_TRG; 

-- DROP SEQUENCE category_table_SEQ; 


-- member_table Table Create SQL
-- 테이블 생성 SQL - member_table
CREATE TABLE member_table
(
    member_id          INT             NOT NULL, 
    member_password    VARCHAR(50)    NOT NULL, 
    member_name        VARCHAR(150)    NOT NULL, 
    member_age         INT             NULL, 
    member_mobile      VARCHAR(15)     NOT NULL, 
    isAdmin            NUMBER          NULL     DEFAULT 0, 
     PRIMARY KEY (member_id)
);

-- Auto Increment를 위한 Sequence 추가 SQL - member_table.member_id
CREATE SEQUENCE member_table_SEQ
START WITH 1
INCREMENT BY 1;

-- Auto Increment를 위한 Trigger 추가 SQL - member_table.member_id
CREATE OR REPLACE TRIGGER member_table_AI_TRG
BEFORE INSERT ON member_table 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT member_table_SEQ.NEXTVAL
    INTO :NEW.member_id
    FROM DUAL;
END;

-- DROP TRIGGER member_table_AI_TRG; 

-- DROP SEQUENCE member_table_SEQ; 


-- wish_table Table Create SQL
-- 테이블 생성 SQL - wish_table
CREATE TABLE wish_table
(
    wishkey      INT    NOT NULL, 
    member_id    INT    NULL, 
    itemkey      INT    NULL, 
     PRIMARY KEY (wishkey)
);

-- Auto Increment를 위한 Sequence 추가 SQL - wish_table.wishkey
CREATE SEQUENCE wish_table_SEQ
START WITH 1
INCREMENT BY 1;

-- Auto Increment를 위한 Trigger 추가 SQL - wish_table.wishkey
CREATE OR REPLACE TRIGGER wish_table_AI_TRG
BEFORE INSERT ON wish_table 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT wish_table_SEQ.NEXTVAL
    INTO :NEW.wishkey
    FROM DUAL;
END;

-- DROP TRIGGER wish_table_AI_TRG; 

-- DROP SEQUENCE wish_table_SEQ; 

-- Foreign Key 설정 SQL - wish_table(member_id) -> member_table(member_id)
ALTER TABLE wish_table
    ADD CONSTRAINT FK_wish_table_member_id_member_table_member_id FOREIGN KEY (member_id)
        REFERENCES member_table (member_id) ;

-- Foreign Key 삭제 SQL - wish_table(member_id)
-- ALTER TABLE wish_table
-- DROP CONSTRAINT FK_wish_table_member_id_member_table_member_id;


-- board_table Table Create SQL
-- 테이블 생성 SQL - board_table
CREATE TABLE board_table
(
    board_id           INT             NOT NULL, 
    board_writer       VARCHAR(50)     NULL, 
    member_id          INT             NULL, 
    board_hits         INT             NULL, 
    board_title        VARCHAR(100)    NULL, 
    boardcreatetime    TIMESTAMP(6)    NULL, 
    board_context      VARCHAR(300)    NULL, 
     PRIMARY KEY (board_id)
);

-- Auto Increment를 위한 Sequence 추가 SQL - board_table.board_id
CREATE SEQUENCE board_table_SEQ
START WITH 1
INCREMENT BY 1;

-- Auto Increment를 위한 Trigger 추가 SQL - board_table.board_id
CREATE OR REPLACE TRIGGER board_table_AI_TRG
BEFORE INSERT ON board_table 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT board_table_SEQ.NEXTVAL
    INTO :NEW.board_id
    FROM DUAL;
END;

-- DROP TRIGGER board_table_AI_TRG; 

-- DROP SEQUENCE board_table_SEQ; 

-- Foreign Key 설정 SQL - board_table(member_id) -> member_table(member_id)
ALTER TABLE board_table
    ADD CONSTRAINT FK_board_table_member_id_member_table_member_id FOREIGN KEY (member_id)
        REFERENCES member_table (member_id) ;

-- Foreign Key 삭제 SQL - board_table(member_id)
-- ALTER TABLE board_table
-- DROP CONSTRAINT FK_board_table_member_id_member_table_member_id;


-- product_table Table Create SQL
-- 테이블 생성 SQL - product_table
CREATE TABLE product_table
(
    product_id         INT              NOT NULL, 
    product_name       VARCHAR(150)     NULL, 
    img1               BLOB             NULL, 
    img2               BLOB             NULL, 
    product_context    VARCHAR(1200)    NULL, 
    product_price      INT              NULL, 
    product_date       date             NULL, 
    category_id        INT              NULL, 
    member_id          INT              NULL, 
     PRIMARY KEY (product_id)
);

-- Auto Increment를 위한 Sequence 추가 SQL - product_table.product_id
CREATE SEQUENCE product_table_SEQ
START WITH 1
INCREMENT BY 1;

-- Auto Increment를 위한 Trigger 추가 SQL - product_table.product_id
CREATE OR REPLACE TRIGGER product_table_AI_TRG
BEFORE INSERT ON product_table 
REFERENCING NEW AS NEW FOR EACH ROW 
BEGIN 
    SELECT product_table_SEQ.NEXTVAL
    INTO :NEW.product_id
    FROM DUAL;
END;

-- DROP TRIGGER product_table_AI_TRG; 

-- DROP SEQUENCE product_table_SEQ; 

-- Foreign Key 설정 SQL - product_table(category_id) -> category_table(category_id)
ALTER TABLE product_table
    ADD CONSTRAINT FK_product_table_category_id_category_table_category_id FOREIGN KEY (category_id)
        REFERENCES category_table (category_id) ;

-- Foreign Key 삭제 SQL - product_table(category_id)
-- ALTER TABLE product_table
-- DROP CONSTRAINT FK_product_table_category_id_category_table_category_id;

-- Foreign Key 설정 SQL - product_table(member_id) -> member_table(member_id)
ALTER TABLE product_table
    ADD CONSTRAINT FK_product_table_member_id_member_table_member_id FOREIGN KEY (member_id)
        REFERENCES member_table (member_id) ;

-- Foreign Key 삭제 SQL - product_table(member_id)
-- ALTER TABLE product_table
-- DROP CONSTRAINT FK_product_table_member_id_member_table_member_id;








-- 구매내역, 댓글 테이블



-- order_table Table Create SQL
-- 테이블 생성 SQL - order_table
CREATE TABLE order_table
(
    `order_id`    INT         NOT NULL    AUTO_INCREMENT, 
    `membe_id`    INT     NOT NULL, 
    `product_id`  INT       NOT NULL, 
    `order_date`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
     PRIMARY KEY (order_id)
);

-- Foreign Key 설정 SQL - order_table(product_id, membe_id) -> product_table(product_id, member_id)
ALTER TABLE order_table
    ADD CONSTRAINT FK_order_table_product_id_product_table_product_id FOREIGN KEY (product_id, membe_id)
        REFERENCES product_table (product_id, member_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - order_table(product_id, membe_id)
-- ALTER TABLE order_table
-- DROP FOREIGN KEY FK_order_table_product_id_product_table_product_id;


-- comment_table Table Create SQL
-- 테이블 생성 SQL - comment_table
CREATE TABLE comment_table
(
    `boardid`             INT             NOT NULL    AUTO_INCREMENT, 
    `id`                  INT             NOT NULL, 
    `commentContents`     VARCHAR(300)    NOT NULL, 
    `commentcreatedtime`  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
     PRIMARY KEY (boardid)
);

-- Foreign Key 설정 SQL - comment_table(id) -> board_table(id)
ALTER TABLE comment_table
    ADD CONSTRAINT FK_comment_table_id_board_table_id FOREIGN KEY (id)
        REFERENCES board_table (id) ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Foreign Key 삭제 SQL - comment_table(id)
-- ALTER TABLE comment_table
-- DROP FOREIGN KEY FK_comment_table_id_board_table_id;

**Comment by ggggene** [comment]
# 상품테이블 추가 사항

기존 테이블에 아래의 코드만 추가
- mysql DB 쓰다가 오류날까봐 일단 오라클로 진행했습니다


-- product_table의 category_id 컬럼 생성
alter table PRODUCT_TABLE add category_id int;

-- product_table의 category_id에 fk 키 제약조건 부여
alter table PRODUCT_TABLE add constraint category_fk foreign key (CATEGORY_ID) references CATEGORY_TABLE (CATEGORY_ID);
select * from PRODUCT_TABLE;

-- product_table의 member_id 컬럼 생성
alter table PRODUCT_TABLE add member_id int;


-- product_table의 member_id에 fk 키 제약조건 부여
product_table에 member_id를 외래키로 추가 alter table PRODUCT_TABLE add constraint fk_product_member_id foreign key (member_id) references MEMBER_TABLE (member_id);

**Comment by 99ibin** [comment]
-- board_table 생성
DROP TABLE board_table CASCADE CONSTRAINTS;
CREATE TABLE board_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    boardWriter VARCHAR2(50),
    boardPass VARCHAR2(20),
    boardTitle VARCHAR2(50),
    boardContents VARCHAR2(500),
    boardCreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    boardHits NUMBER DEFAULT 0,
    fileAttached NUMBER DEFAULT 0
);


-- comment_table 생성
DROP TABLE comment_table CASCADE CONSTRAINTS;
CREATE TABLE comment_table (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commentWriter VARCHAR2(50),
    commentContents VARCHAR2(200),
    boardId NUMBER,
    commentCreatedTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
);
기존 테이블에서 변경사항이 있어서 DROP하시고 생성해주시면 됩니다.
